### ISSUE TITLE
Форма Legal Entity

### ISSUE THREAD

**Issue by biben1989** [Vitaliy-1/openHealth#44]
- [x] 1. Треба продумати  обробник помилки якщо нема данних в EDR! 
- [x] 2. Зробити UI select search, datetepicker - при рендирінгу не оновлюеться , а стае звичайним текстови полем
- [x] 3. При спробі відправити без Onwer tax_id зі значеням поля not_tax_id true ЕСОЗ валідуе  tax_id і пише що це поле не може бути порожнім,хоча в документації ми можемо передати без  tax_id !
- [ ] перевіряти ЄДРПОУ / РНОКПП при підписанні КЕП
- [ ] Якщо ми не авторизоварі через ЕСОЗ ми не можемо визвати метод Get legal Entity **Authorization header is not set or doesn't contain Bearer token** Треба знайти інший спосіб підтягувати данні !
- [x] Валадіція на англійські літери в поле Іʼмя Прізвище, Документи і тк.д
